### ISSUE TITLE
Normalize demux API

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qiita-files#5]
The current API for the demux mainly accepts an `h5py.File` as parameter, which puts the burden of opening the hdf5 file to the consumer of the API. I think it will make more sense to actually pass in the filepath of the hdf5 file and handle the file opening/closing internally. This will allow us to parallelize more stuff internally, as we did for the `to_per_sample_files` function (which is the only exposed API function that allows a filepath rather than a `h5py.File` object.

@wasade, @antgonza Any objections to this?

**Comment by antgonza** [comment]
None.
